### ISSUE TITLE
Fix SLF4J warnings

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/jpl-validator#1]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by davrodgon** [comment]
Some library using the SLF4J API, but there is no runtime implementation in the classpath. 
You can add something like the following to dependencies in build.gradle:

compile 'org.slf4j:slf4j-api:1.7.30'
runtimeOnly 'org.slf4j:slf4j-simple:1.7.30'

**Comment by orviz** [comment]
Commit b3231e0 added in `release/1.1.0` branch
