### ISSUE TITLE
tox file path is a required parameter

### ISSUE THREAD

**Issue by samuelbernardolip** [EOSC-synergy/jpl-validator#39]
https://github.com/EOSC-synergy/jpl-validator/blob/4926dcbca8ef0c88c8fa22ced52862aeb1ef207c/src/main/resources/schema.json#L25

Add tox_file as a required parameter. This always need to have the real path inside container to the tox.ini file.

More details on https://github.com/indigo-dc/jenkins-pipeline-library/pull/150

**Comment by orviz** [comment]
Released in 1.1.0
